from pathlib import Path

path = Path("app/main.py")
text = path.read_text()

start = text.find("def diagnose(req: DiagnosisRequest) -> DiagnosisResponse:")
end = text.find('\n\n@app.get("/health")', start)

if start == -1:
    raise SystemExit("Could not find the diagnose function.")

if end == -1:
    raise SystemExit("Could not find the health route after diagnose().")

lines = [
'def diagnose(req: DiagnosisRequest) -> DiagnosisResponse:',
'    answer_text = " ".join(str(value) for value in req.answers.values())',
'    symptom_text = f"{req.symptom} {answer_text}".lower()',
'    media = req.answers.get("media", [])',
'    media_count = len(media) if isinstance(media, list) else 0',
'    matches: list[Cause] = []',
'',
'    def has(*phrases: str) -> bool:',
'        return any(phrase in symptom_text for phrase in phrases)',
'',
'    def add_cause(',
'        title: str,',
'        confidence: float,',
'        why: str,',
'        checks: list[str],',
'        repair: list[str],',
'        safety: Literal["low", "medium", "high", "stop"] = "medium",',
'    ) -> None:',
'        if not any(item.title == title for item in matches):',
'            matches.append(',
'                Cause(',
'                    title=title,',
'                    confidence=confidence,',
'                    why=why,',
'                    checks=checks,',
'                    repair=repair,',
'                    safety=safety,',
'                )',
'            )',
'',
'    if req.category == "automotive":',
'        if has("cranks but", "crank but", "turns over but"):',
'            add_cause(',
'                "Crank-no-start condition",',
'                0.86,',
'                "The starter is rotating the engine, so diagnosis should focus on fuel, ignition spark, injector command, compression, timing, and engine-speed signals.",',
'                [',
'                    "Scan for stored and pending trouble codes.",',
'                    "Check whether engine RPM appears in scan data while cranking.",',
'                    "Test for strong ignition spark with an approved spark tester.",',
'                    "Measure fuel pressure against the vehicle specification.",',
'                    "Check injector pulse and engine compression.",',
'                ],',
'                [',
'                    "Repair the fuel, ignition, sensor, wiring, timing, or compression fault confirmed by testing.",',
'                    "Do not replace the fuel pump or ignition components without confirming the failed system.",',
'                ],',
'                "high",',
'            )',
'        elif has("won\\'t start", "wont start", "will not start", "no start", "not starting"):',
'            add_cause(',
'                "Starting-system diagnosis required",',
'                0.78,',
'                "The next step is determining whether this is a no-crank, slow-crank, clicking, or crank-no-start condition.",',
'                [',
'                    "State whether the engine cranks, clicks, turns slowly, or does nothing.",',
'                    "Measure battery voltage before and during a start attempt.",',
'                    "Inspect battery terminals, engine grounds, and starter cables.",',
'                    "Check the security or immobilizer indicator.",',
'                    "Scan all available modules for trouble codes.",',
'                ],',
'                [',
'                    "Repair the circuit or system that fails testing.",',
'                    "Avoid replacing the battery, starter, or fuel pump without confirmation.",',
'                ],',
'                "high",',
'            )',
'',
'        if has("battery dead", "battery dies", "keeps dying", "not charging", "charge light"):',
'            add_cause(',
'                "Battery, charging-system, or parasitic-draw fault",',
'                0.84,',
'                "A repeatedly discharged battery may be caused by a weak battery, poor connections, alternator failure, belt trouble, or an electrical draw while parked.",',
'                [',
'                    "Fully charge and load-test the battery.",',
'                    "Measure charging voltage with the engine running.",',
'                    "Inspect the alternator belt, battery cables, and grounds.",',
'                    "Perform cable voltage-drop tests.",',
'                    "Perform a key-off parasitic-current test after the modules enter sleep mode.",',
'                ],',
'                [',
'                    "Repair poor cable or ground connections.",',
'                    "Replace a failed battery or alternator only after testing.",',
'                    "Isolate and repair any excessive key-off electrical draw.",',
'                ],',
'                "high",',
'            )',
'',
'        if has("overheat", "overheating", "runs hot", "pushing coolant"):',
'            add_cause(',
'                "Cooling-system fault",',
'                0.88,',
'                "Overheating may result from low coolant, leakage, trapped air, fan failure, thermostat trouble, poor circulation, restriction, or combustion gases.",',
'                [',
'                    "Do not open the cooling system while hot.",',
'                    "Check coolant level only after the engine is completely cool.",',
'                    "Pressure-test the cooling system and cap.",',
'                    "Verify cooling-fan operation.",',
'                    "Check thermostat operation and coolant circulation.",',
'                    "Test for combustion gases if coolant is repeatedly expelled.",',
'                ],',
'                [',
'                    "Repair leaks and refill using the correct bleeding procedure.",',
'                    "Replace failed cooling components only after confirming the fault.",',
'                    "Stop driving if the engine temperature is excessive.",',
'                ],',
'                "stop",',
'            )',
'',
'        if has("misfire", "rough idle", "runs rough", "shaking", "flashing check engine", "p030"):',
'            add_cause(',
'                "Engine misfire",',
'                0.86,',
'                "The engine may have an ignition, fuel, intake-air, compression, timing, wiring, or sensor problem.",',
'                [',
'                    "Scan codes and review cylinder misfire counters.",',
'                    "Inspect spark plugs, coils, boots, and connectors.",',
'                    "Check for intake and vacuum leaks.",',
'                    "Verify injector operation and fuel pressure.",',
'                    "Perform compression or leak-down testing if needed.",',
'                ],',
'                [',
'                    "Repair the confirmed ignition, fuel, air, electrical, or mechanical fault.",',
'                    "Do not continue driving with a severe misfire and flashing check-engine light.",',
'                ],',
'                "high",',
'            )',
'',
'        if has("brake", "brakes", "pedal soft", "grinding when stopping", "no brakes"):',
'            add_cause(',
'                "Brake-system fault",',
'                0.90,',
'                "Grinding, poor stopping, fluid loss, warning lamps, or abnormal pedal travel requires immediate brake inspection.",',
'                [',
'                    "Do not drive if braking ability is reduced.",',
'                    "Check brake-fluid level and inspect for leakage.",',
'                    "Inspect pads, shoes, rotors, drums, calipers, hoses, and wheel cylinders.",',
'                    "Check pedal firmness and brake-booster operation.",',
'                    "Scan the ABS module when warning lamps are present.",',
'                ],',
'                [',
'                    "Repair worn, leaking, seized, or damaged brake components.",',
'                    "Bleed the system correctly after hydraulic repairs.",',
'                    "Tow the vehicle when braking performance is unsafe.",',
'                ],',
'                "stop" if has("no brakes", "pedal to floor", "won\\'t stop", "wont stop") else "high",',
'            )',
'',
'        if has("belt", "squeal", "chirp", "shredding", "shreds"):',
'            add_cause(',
'                "Accessory-belt tracking or tension fault",',
'                0.84,',
'                "Belt noise or edge damage commonly indicates incorrect routing, poor tension, pulley misalignment, bearing drag, contamination, or the wrong belt.",',
'                [',
'                    "Verify the correct belt and routing diagram.",',
'                    "Inspect the belt edges and ribs.",',
'                    "Spin each pulley and check for roughness or play.",',
'                    "Observe tensioner movement and pulley alignment.",',
'                    "Check for oil or coolant contamination.",',
'                ],',
'                [',
'                    "Correct the failed pulley, tensioner, bearing, bracket, or alignment problem.",',
'                    "Replace the belt after correcting the root cause.",',
'                ],',
'                "high",',
'            )',
'',
'        if has("speedometer", "odometer", "cruise control", "vehicle speed"):',
'            add_cause(',
'                "Vehicle-speed signal fault",',
'                0.88,',
'                "The speedometer, odometer, cruise control, ABS, transmission, and engine controller may share vehicle-speed data.",',
'                [',
'                    "Scan all modules for speed-sensor and communication codes.",',
'                    "Compare wheel-speed and vehicle-speed live data.",',
'                    "Inspect relevant sensor wiring and connectors.",',
'                    "Inspect tone rings where wheel-speed sensors are used.",',
'                    "Verify module power, grounds, and network communication.",',
'                ],',
'                [',
'                    "Repair damaged wiring, connectors, tone rings, sensors, or module communication.",',
'                    "Replace a sensor only after testing its circuit and signal.",',
'                ],',
'                "medium",',
'            )',
'',
'    elif req.category == "appliance":',
'        if has("won\\'t drain", "wont drain", "not draining", "standing water", "water left"):',
'            add_cause(',
'                "Drain restriction or drain-pump fault",',
'                0.86,',
'                "Standing water is commonly caused by a blocked filter, drain hose, disposer connection, check valve, pump, or control circuit.",',
'                [',
'                    "Disconnect electrical power before accessing internal components.",',
'                    "Check and clean the filter and sump.",',
'                    "Inspect the drain hose for kinks or blockage.",',
'                    "Verify the sink or disposer connection is open.",',
'                    "Test whether the pump receives voltage when draining is commanded.",',
'                ],',
'                [',
'                    "Remove restrictions and correct the hose installation.",',
'                    "Replace the drain pump only if it receives proper power but cannot operate.",',
'                ],',
'                "high",',
'            )',
'',
'        if has("no heat", "not heating", "not drying", "cold"):',
'            add_cause(',
'                "Heating-circuit or airflow fault",',
'                0.84,',
'                "The appliance may have a failed heater, igniter, thermostat, thermal fuse, sensor, relay, airflow path, or supply circuit.",',
'                [',
'                    "Disconnect power or shut off fuel before service.",',
'                    "Verify correct supply voltage or gas supply.",',
'                    "Check airflow and clean restrictions.",',
'                    "Test thermal protection devices and temperature sensors.",',
'                    "Test the heating circuit using the wiring diagram.",',
'                ],',
'                [',
'                    "Restore airflow before replacing parts.",',
'                    "Replace only components that fail electrical or operational testing.",',
'                ],',
'                "high",',
'            )',
'',
'        if has("not cooling", "not freezing", "warm refrigerator", "freezer warm"):',
'            add_cause(',
'                "Refrigeration airflow, defrost, fan, or sealed-system fault",',
'                0.80,',
'                "Poor cooling may result from blocked airflow, dirty coils, fan failure, frost buildup, door leakage, control problems, or a sealed-system fault.",',
'                [',
'                    "Record refrigerator and freezer temperatures.",',
'                    "Inspect door seals and airflow vents.",',
'                    "Clean accessible condenser coils.",',
'                    "Confirm evaporator and condenser fan operation.",',
'                    "Inspect the evaporator frost pattern.",',
'                ],',
'                [',
'                    "Repair airflow, fan, defrost, seal, sensor, or control problems.",',
'                    "Use a qualified refrigeration technician for sealed-system work.",',
'                ],',
'                "medium",',
'            )',
'',
'    elif req.category == "equipment":',
'        if has("won\\'t start", "wont start", "no start", "not starting"):',
'            add_cause(',
'                "Small-engine fuel, spark, compression, or safety-switch fault",',
'                0.84,',
'                "A small engine requires fresh fuel, ignition spark, compression, airflow, and enabled safety controls.",',
'                [',
'                    "Use fresh fuel and verify the correct fuel mixture.",',
'                    "Inspect and test the spark plug.",',
'                    "Check the air filter, choke, primer, and fuel flow.",',
'                    "Inspect safety switches and the ignition kill wire.",',
'                    "Test compression if fuel and spark are present.",',
'                ],',
'                [',
'                    "Replace stale fuel and a fouled spark plug.",',
'                    "Clean or rebuild the carburetor if fuel delivery is restricted.",',
'                    "Repair failed ignition, safety-switch, or mechanical components based on testing.",',
'                ],',
'                "medium",',
'            )',
'',
'        if has("starts then dies", "runs then dies", "only runs on choke", "won\\'t stay running", "wont stay running"):',
'            add_cause(',
'                "Restricted carburetor or fuel delivery",',
'                0.87,',
'                "An engine that starts but does not remain running often has restricted fuel flow, blocked carburetor passages, a tank-vent problem, or an intake-air leak.",',
'                [',
'                    "Briefly loosen the fuel cap to test tank venting.",',
'                    "Check continuous fuel flow to the carburetor.",',
'                    "Inspect fuel lines and the fuel filter.",',
'                    "Inspect carburetor jets and passages.",',
'                    "Check intake gaskets for air leakage.",',
'                ],',
'                [',
'                    "Clean or rebuild the carburetor.",',
'                    "Replace damaged fuel lines, filters, primers, or vent components.",',
'                ],',
'                "medium",',
'            )',
'',
'    elif req.category in ("home", "diy"):',
'        if has("sparking", "spark", "smoke", "burning smell", "hot outlet"):',
'            add_cause(',
'                "Electrical arcing or overheating hazard",',
'                0.96,',
'                "Sparking, smoke, heat, or a burning odor may indicate a dangerous loose electrical connection or short circuit.",',
'                [',
'                    "Turn off the affected breaker if it can be done safely.",',
'                    "Do not touch exposed wires or energized equipment.",',
'                    "Keep combustible materials away.",',
'                    "Call emergency services if there is active fire.",',
'                    "Have the circuit inspected by a qualified electrician.",',
'                ],',
'                [',
'                    "Do not restore power until damaged wiring and devices are repaired and tested.",',
'                ],',
'                "stop",',
'            )',
'',
'        if has("water leak", "pipe leak", "leaking pipe", "dripping pipe"):',
'            add_cause(',
'                "Plumbing leak",',
'                0.82,',
'                "The leak may involve a pressurized water line, drain, valve, hose, fitting, fixture seal, condensation, or water entering from another location.",',
'                [',
'                    "Shut off the nearest water valve if the leak is active.",',
'                    "Protect electrical equipment and flooring.",',
'                    "Dry the area and locate the highest wet point.",',
'                    "Determine whether it leaks continuously or only during use.",',
'                    "Inspect fittings, valves, traps, hoses, and seals.",',
'                ],',
'                [',
'                    "Repair or replace the confirmed leaking pipe, seal, valve, hose, or fitting.",',
'                    "Dry wet materials promptly to reduce mold and structural damage.",',
'                ],',
'                "high",',
'            )',
'',
'    for rule in RULES:',
'        if rule["category"] != req.category:',
'            continue',
'',
'        matched = sum(',
'            1 for needle in rule["needles"]',
'            if needle.lower() in symptom_text',
'        )',
'',
'        if matched:',
'            original = rule["cause"]',
'            ratio = matched / max(len(rule["needles"]), 1)',
'            confidence = round(min(original.confidence, 0.62 + 0.30 * ratio), 2)',
'',
'            if not any(item.title == original.title for item in matches):',
'                matches.append(',
'                    Cause(',
'                        title=original.title,',
'                        confidence=confidence,',
'                        why=original.why,',
'                        checks=original.checks,',
'                        repair=original.repair,',
'                        safety=original.safety,',
'                    )',
'                )',
'',
'    matches.sort(key=lambda item: item.confidence, reverse=True)',
'    matches = matches[:3]',
'',
'    if not matches:',
'        fallback_checks = {',
'            "automotive": [',
'                "Enter the year, make, model, engine size, and mileage.",',
'                "State whether it cranks, starts, clicks, stalls, overheats, leaks, or has warning lights.",',
'                "Enter all trouble codes exactly as displayed.",',
'                "Describe whether it occurs cold, hot, at idle, while accelerating, braking, or driving.",',
'            ],',
'            "motorcycle": [',
'                "Enter the year, make, model, engine size, and mileage.",',
'                "State whether it cranks, starts, stalls, misfires, leaks, or loses power.",',
'                "Include warning lights, codes, and recent repairs.",',
'            ],',
'            "appliance": [',
'                "Enter the appliance type, brand, and complete model number.",',
'                "Enter the exact error code.",',
'                "State whether it powers on and which function fails.",',
'                "Describe when the failure occurs during the cycle.",',
'            ],',
'            "equipment": [',
'                "Enter the equipment type, brand, model, and engine model.",',
'                "State whether it cranks, starts, runs briefly, smokes, surges, or loses power.",',
'                "Include fuel age, spark-plug condition, and recent repairs.",',
'            ],',
'            "home": [',
'                "Identify whether this involves electrical, plumbing, HVAC, flooring, roofing, or structure.",',
'                "Describe the exact location and when the condition occurs.",',
'                "State whether water, electricity, gas, heat, smoke, or movement is involved.",',
'            ],',
'            "diy": [',
'                "Describe the intended result and the current problem.",',
'                "List the materials, dimensions, tools, and fasteners involved.",',
'                "State whether electrical, gas, structural, chemical, or lifting hazards are present.",',
'            ],',
'        }',
'',
'        media_note = ""',
'        if media_count:',
'            media_note = (',
'                f"{media_count} attachment was received. "',
'                if media_count == 1',
'                else f"{media_count} attachments were received. "',
'            )',
'',
'        matches = [',
'            Cause(',
'                title="More specific details needed",',
'                confidence=0.60 if media_count else 0.56,',
'                why=(',
'                    media_note',
'                    + "The symptom does not yet contain enough detail for a reliable repair path. Automatic visual analysis will be connected in a later update."',
'                ),',
'                checks=fallback_checks[req.category],',
'                repair=[',

'                    "Add the requested information and submit the diagnosis again.",',
'                ],',
'                safety="medium",',
'            )',
'        ]',
'',
'    safety_order = {"low": 0, "medium": 1, "high": 2, "stop": 3}',
'    highest_safety = max(',
'        (item.safety for item in matches),',
'        key=lambda level: safety_order[level],',
'    )',
'',
'    safety_message = {',
'        "low": "Normal precautions apply.",',
'        "medium": "Use appropriate PPE and disable power before disassembly.",',
'        "high": "Do not operate until the fault is inspected. Disconnect power or disable the machine before service.",',
'        "stop": "STOP WORK. Leave the area safe and contact a qualified professional or emergency services when appropriate.",',
'    }[highest_safety]',
'',
'    media_summary = ""',
'    if media_count == 1:',
'        media_summary = " One attachment was included."',
'    elif media_count > 1:',
'        media_summary = f" {media_count} attachments were included."',
'',
'    return DiagnosisResponse(',
'        id=str(uuid4()),',
'        created_at=datetime.now(timezone.utc).isoformat(),',
'        category=req.category,',
'        symptom=req.symptom,',
'        summary=(',
'            f"Pocket Mechanic found {len(matches)} likely diagnostic "',
'            f"path{\'s\' if len(matches) != 1 else \'\'}."',
'            f"{media_summary}"',
'        ),',
'        safety_message=safety_message,',
'        causes=matches,',
'    )',
]

new_function = "\n".join(lines)
text = text[:start] + new_function + text[end:]

text = text.replace(
    'return {"status": "ok", "version": "0.4.0"}',
    'return {"status": "ok", "version": "0.5.1"}',
)

path.write_text(text)

print("SUCCESS: Smarter diagnosis engine installed.")
