const {JSDOM}=require('jsdom');
const fs=require('fs');
const assert=require('node:assert/strict');
(async()=>{
  const dom=new JSDOM(fs.readFileSync('static/index.html','utf8'),{url:'https://pocket.test/',runScripts:'outside-only'});
  const w=dom.window,q=s=>w.document.querySelector(s),tick=()=>new Promise(r=>setTimeout(r,0));
  w.pocketGuruUser={id:'test-user',email:'test@example.com',verified:true};
  w.scrollTo=()=>{};w.HTMLElement.prototype.scrollIntoView=()=>{};w.alert=msg=>{throw Error(msg)};
  let payload;
  w.fetch=async(url,opt)=>({ok:true,json:async()=>url==='/health'?{status:'ok'}:(payload=JSON.parse(opt.body),{id:'test',category:payload.category,symptom:payload.symptom,summary:'OK',safety_message:'OK',causes:[{title:'test',confidence:.5,why:'test',checks:[],repair:[]}]})});
  w.eval(fs.readFileSync('static/app.js','utf8'));
  const diagnose=async()=>{q('#diagnosisForm').dispatchEvent(new w.Event('submit',{cancelable:true}));await tick();};
  q('#addDiagnosisItem').click();q('#garageName').value='Dad truck';q('#garageYear').value='2021';q('#garageMake').value='Ford';q('#garageModel').value='F250';q('#symptom').value='Engine does not crank';q('#saveDiagnosisItem').checked=true;
  await diagnose();
  assert.equal(q('#profileSelect option:checked').textContent,'Dad truck');assert.equal(q('#garageCount').textContent,'1');assert.equal(payload.answers.item.model,'F250');
  q('#addDiagnosisItem').click();assert.equal(q('#garageName').value,'');assert.equal(q('#symptom').value,'');assert(q('#result').classList.contains('hidden'));assert.equal(q('#profileSelect').value,'');assert.equal(q('#garageCount').textContent,'1');
  q('#category').value='appliance';q('#category').dispatchEvent(new w.Event('change'));q('#addDiagnosisItem').click();assert(q('#garageYear').disabled);assert(q('#garageYear').parentElement.hidden);assert.equal(q('#garageMake').parentElement.firstChild.textContent,'Brand');
  q('#garageName').value='Dad washer';q('#garageEngine').value='Washer';q('#symptom').value='washer does not drain';q('#saveDiagnosisItem').checked=true;
  await diagnose();assert.equal(payload.answers.item.name,'Dad washer');assert.equal(payload.answers.item.year,'');assert.equal(q('#garageCount').textContent,'2');assert.equal(JSON.parse(w.localStorage.getItem('pocket-guru-garage-v1:test-user')).length,2);
  q('[data-use]').click();assert.equal(q('#profileSelect option:checked').textContent,'Dad washer');
  q('#category').value='diy';q('#category').dispatchEvent(new w.Event('change'));assert(q('#addDiagnosisItem').hidden);assert(q('#saveDiagnosisItemLabel').hidden);
  console.log('PASS: unified diagnosis, optional garage save, new-item reset, appliance fields, account-specific persistence, garage navigation');w.close();
})().catch(e=>{console.error(e);process.exit(1)});
