const {JSDOM}=require('jsdom');const fs=require('fs');const assert=require('assert');const root=require('path').resolve(__dirname,'../static')+'/';
(async()=>{
const dom=new JSDOM(fs.readFileSync(root+'index.html','utf8'),{url:'https://pocket.test/',runScripts:'outside-only'});const w=dom.window;w.scrollTo=()=>{};w.HTMLElement.prototype.scrollIntoView=()=>{};let payload;
w.pocketGuruUser={id:'test-user',email:'test@example.com',verified:true};w.fetch=async(url,opt)=>({ok:true,json:async()=>url==='/health'?{status:'ok'}:(payload=JSON.parse(opt.body),{id:'test',category:payload.category,symptom:payload.symptom,summary:'OK',safety_message:'OK',causes:[{title:'test',confidence:0.5,why:'test',checks:[],repair:[]}]})});w.alert=msg=>{throw Error(msg)};
w.eval(fs.readFileSync(root+'app.js','utf8'));w.document.querySelectorAll('script:not([src])').forEach(script=>w.eval(script.textContent));w.document.dispatchEvent(new w.Event('DOMContentLoaded'));const q=s=>w.document.querySelector(s);const change=s=>q(s).dispatchEvent(new w.Event('change'));const save=()=>q('#garageForm').dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));
q('#addDiagnosisItem').click();q('#garageName').value='Dad truck';q('#garageYear').value='2021';q('#garageMake').value='Ford';q('#garageModel').value='F250';save();assert.equal(q('#profileSelect option:checked').textContent,'Dad truck');assert.equal(q('#garageCount').textContent,'1');assert(q('#diagnosisItemEditor').hidden);
q('#symptom').value='Previous vehicle fault';q('#result').innerHTML='Old result';q('#result').classList.remove('hidden');q('#status').textContent='Old status';
q('#addDiagnosisItem').click();assert.equal(q('#garageName').value,'');assert.equal(q('#garageYear').value,'');assert.equal(q('#symptom').value,'');assert.equal(q('#result').innerHTML,'');assert(q('#result').classList.contains('hidden'));assert.equal(q('#profileSelect').value,'');assert.equal(q('#status').textContent,'');assert.equal(q('#itemEditorActions button[type=submit]').textContent,'Save to My Garage');assert.equal(q('#garageCount').textContent,'1');q('#itemEditorActions button[type=button]').click();
q('#category').value='appliance';change('#category');assert.equal(q('#profileSelect').options.length,1);q('#addDiagnosisItem').click();assert(q('#garageYear').disabled);assert(q('#garageYear').parentElement.hidden);assert.equal(q('#garageMake').parentElement.firstChild.textContent,'Brand');q('#garageName').value='Dad washer';q('#garageEngine').value='Washer';save();assert.equal(q('#profileSelect option:checked').textContent,'Dad washer');assert.equal(q('#garageCount').textContent,'2');
q('#symptom').value='washer does not drain';q('#diagnosisForm').dispatchEvent(new w.Event('submit',{cancelable:true}));await new Promise(r=>setTimeout(r,0));assert.equal(payload.answers.item.name,'Dad washer');assert.equal(payload.answers.item.year,'');assert.equal(JSON.parse(w.localStorage.getItem('pocket-guru-garage-v1:test-user')).length,2);
q('[data-use]').click();assert.equal(q('#profileSelect option:checked').textContent,'Dad washer');assert.equal(q('#connection').textContent,'Connected');q('#category').value='diy';change('#category');assert.equal(q('#assistTitle').textContent,'Project Planner');assert(q('#addDiagnosisItem').hidden);q('#category').value='automotive';change('#category');assert.equal(q('#assistTitle').textContent,'Find a fix');assert.equal(q('#diagnoseButton').textContent,'Find my next steps');console.log('PASS: vehicle save/select, appliance fields, category filtering, garage persistence, diagnosis item payload, garage Diagnose navigation');w.close();
})().catch(e=>{console.error(e);process.exit(1)});
